### ISSUE TITLE
Adds scipy to requirements

### ISSUE THREAD

**Issue by anaschwendler** [datasciencebr/rosie#33]
Recently running rosie on my new notebook, I noticed that I couldn't run without scipy. So for those who doesn't have it installed by default we need to have :)

**Comment by cuducos** [comment]
Not sure if this is (or _should be_) required. Rosie uses Anaconda Python and [`scipy` is a package installed by default in Anaconda Python](https://docs.continuum.io/anaconda/pkg-docs).

However this issue called my attention to two details:

* In spite of that [`scipy` is already in `requirements.txt`](https://github.com/datasciencebr/rosie/blob/master/requirements.txt#L5) maybe to make sure we run with a specific version
* One can infer that we use Anaconda Python [from the non-Docker instructions](https://github.com/datasciencebr/rosie#setup), but [our `Dockerfile` use standard Python](https://github.com/datasciencebr/rosie/blob/master/Dockerfile)

In my opinion I should close this issue because `scipy` is already there. But may I open anther one regarding standard Python vs. Anaconda Python, or am I missing something here?

**Comment by Irio** [comment]
As mentioned by @cuducos, SciPy is already listed in the requirements file.
